<script src="https://cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.8/hammer.min.js"></script>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" /><script>
  Qualtrics.SurveyEngine.addOnload(function() {
    document.activeElement.blur();
    setTimeout(function() {
      window.scrollTo(0, 0); 
    }, 0);
  });

Qualtrics.SurveyEngine.addOnReady(function() {
    jQuery('#Plug').attr('style', 'display:none !important');
});
</script>
